#!/bin/bash

# Copies the files into the Autograder's CWD 
find /autograder/submission -type f ! -name '*.c' -delete
cp -r /autograder/submission/* /autograder/source/

cd /autograder/source

python3 run_tests.py > /autograder/results/results.json
