#!/bin/bash

# Copies the files into the Autograder's CWD 
find /autograder/submission -type f ! -name '*.c' ! -name 'makefile' ! -name 'Makefile' -delete
find /autograder/submission -type f -exec cp {} /autograder/source \;

cd /autograder/source

python3 run_tests.py > /autograder/results/results.json
